# Generated by Django 3.2.9 on 2021-11-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(max_length=200)),
                ('op1', models.CharField(max_length=200)),
                ('op2', models.CharField(max_length=200)),
                ('op3', models.CharField(max_length=200)),
                ('op4', models.CharField(max_length=200)),
                ('Answer', models.CharField(max_length=200)),
                ('Clicked', models.BooleanField(blank=True, default=False, null=True)),
                ('is_right', models.BooleanField(blank=True, default=False, null=True)),
                ('Category', models.ManyToManyField(to='quiz_app.Category')),
            ],
        ),
    ]
