# Generated by Django 3.2.9 on 2021-11-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='Category',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Question',
            field=models.TextField(max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='Category',
            field=models.ManyToManyField(to='quiz_app.Category'),
        ),
    ]
